### ISSUE TITLE
Which one should I refer to for the simulation paper?

### ISSUE THREAD

**Issue by zhangtianxian** [FilippoAiraldi/mpc-reinforcement-learning#3]

**Comment by FilippoAiraldi** [comment]
Hello!

I am not sure what your question is about. What are you referring to with "which one"? Of the examples, maybe? And what simulation paper are you talking about?

**Comment by zhangtianxian** [comment]
Hello!
I am looking at the code of your
https://github.com/FilippoAiraldi/mpc-reinforcement-learning project, which
one is the literature you simulated?

Filippo Airaldi ***@***.***> 於 2023年8月29日週二 下午3:15寫道：

**Comment by FilippoAiraldi** [comment]
Thanks for the clarification! If you take a look at the README, I wrote down some references. Most of the theory as well as the example is taken from the first [reference](https://arxiv.org/abs/1904.04152).

Hope this helped :)

**Comment by zhangtianxian** [comment]
Thank you for your response! I find the ideas in your article to be very
creative and worth learning from. However, I encountered some issues during
the implementation process. Luckily, you have open-sourced the code, which
has provided me with guidance.
I'm truly grateful for your help!

Filippo Airaldi ***@***.***> 於 2023年8月29日週二 下午4:49寫道：
