### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zhangzhiwei-bit** [FilippoAiraldi/mpc-reinforcement-learning#4]
How to implement a nonlinear MPC system? the code in examples implement a simple linear MPC system.

**Comment by FilippoAiraldi** [comment]
Just create either a nonlinear objective, dynamics, or constraint and you'll have a nonlinear MPC. See [here](https://github.com/FilippoAiraldi/mpcrl-for-ramp-metering/blob/09bc24f396eb4352bc22eec95835c5c538ca64fa/mpc/highway_traffic_mpc.py) for example (nonlinear dynamics).
